### ISSUE TITLE
Change belarusian classical wikipedia from be-x-old to be-tarask

### ISSUE THREAD

**Issue by tbicr** [osmlab/wmf-sitematrix#1]
Hi

Belarusian classical wikipedia was changed from `be-x-old` to `be-tarask`. So now https://be-x-old.wikipedia.org/ links redirect to https://be-tarask.wikipedia.org/. But in `wikipedia.json` it still `be-x-old`. Can it be fixed?

**Comment by tyrasd** [comment]
As explained in https://github.com/openstreetmap/iD/pull/2875 already, this isn't really something that can be fixed here, as this repository only mirrors the result of meta.wikimedia's  [site matrix](https://meta.wikimedia.org/wiki/Special:SiteMatrix) ([json](https://meta.wikimedia.org/w/api.php?action=sitematrix&uselang=en&format=json)) which still has the old `be-x-old` as the language code for Belarusian's classical orthography.

**Comment by bhousel** [comment]
upstream issues for reference
https://phabricator.wikimedia.org/T132008
https://phabricator.wikimedia.org/T111876

**Comment by 1ec5** [comment]
> Belarusian classical wikipedia was changed from `be-x-old` to `be-tarask`.

For reference, this happened in <https://gerrit.wikimedia.org/r/c/pywikibot/core/+/243055/> for <https://phabricator.wikimedia.org/T11823>.

> But in `wikipedia.json` it still `be-x-old`.

8ed5dcf02117931dfd7059322fbd18396aaf6970 changed `be-x-old:` to `be-tarask:` based on <https://gerrit.wikimedia.org/r/c/operations/mediawiki-config/+/236966/> for <https://phabricator.wikimedia.org/T111876>.
