### ISSUE TITLE
WMF-Labs

### ISSUE THREAD

**Issue by Abbe98** [osmlab/wmf-sitematrix#2]
Is this available as a static service at wmflabs.org? It would be really useful to have, if not is it okey that I publish it there?

**Comment by 1ec5** [comment]
Sure, that’d be fine. However, if you’re going to provide something like this on Tools Labs, it’d make sense to update it periodically with a cronjob. Currently this project has to be updated manually (via a `make` invocation).

**Comment by Abbe98** [comment]
True, I will set it to run every 14 days.

**Comment by Abbe98** [comment]
For those interested this is now available at  tools.wmflabs.org/wmf-sitematrix/ and the files are updated every 15 days.

**Comment by 1ec5** [comment]
Thanks for setting this up!

**Comment by ghost** [comment]
Wait, so how is https://wmf-sitematrix.toolforge.org static compared to https://meta.wikimedia.org/wiki/Special:SiteMatrix ?

**Comment by Abbe98** [comment]
https://wmf-sitematrix.toolforge.org is just a mirror of this repository
hosted on Wikimedia infrastructure, in practice, it filters out things like
closed wikis.

Den tis 23 feb. 2021 kl 08:03 skrev Arlo James Barnes <
notifications@github.com>:
